[build]
builder = "nixpacks"
buildCommand = "./scripts/railway-build.sh"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health.json"
healthcheckTimeout = 300
healthcheckInterval = 60
